# Generated by Django 4.2.4 on 2024-06-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_disease_delete_diseasedescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
