# Generated by Django 4.2.4 on 2024-06-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
    ]
