# Generated by Django 4.2.4 on 2024-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_disease_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
